export const genreList = [
  { group: "", value: "none", label: "None" },
  { group: "By Age", value: "Children's fiction", label: "Children's fiction" },
  { group: "By Age", value: "Fratire fiction", label: "Fratire fiction" },
  { group: "By Age", value: "Lad lit fiction", label: "Lad lit fiction" },
  { group: "By Age", value: "New adult fiction", label: "New adult fiction" },
  {
    group: "By Age",
    value: "Young adult fiction",
    label: "Young adult fiction",
  },
  { group: "Comedy", value: "Comedy", label: "Comedy" },
  { group: "Comedy", value: "Burlesque", label: "Burlesque" },
  { group: "Comedy", value: "Fantasy comedy", label: "Fantasy comedy" },
  { group: "Comedy", value: "Comedy horror", label: "Comedy horror" },
  { group: "Comedy", value: "Parody", label: "Parody" },
  { group: "Comedy", value: "Metaparody", label: "Metaparody" },
  { group: "Comedy", value: "Sci-fi comedy", label: "Sci-fi comedy" },
  { group: "Comedy", value: "Surreal comedy", label: "Surreal comedy" },
  { group: "Comedy", value: "Tall tale comedy", label: "Tall tale comedy" },
  { group: "Comedy", value: "Tragicomedy", label: "Tragicomedy" },
  { group: "Comedy", value: "Satire", label: "Satire" },
  { group: "Comedy", value: "Romantic Comedy", label: "Romantic Comedy" },
  {
    group: "Comedy",
    value: "Science fiction comedy ",
    label: "Science fiction comedy",
  },

  { group: "Mystery", value: "Mystery ", label: "Mystery " },
  {
    group: "Mystery",
    value: "Historical mystery",
    label: "Historical mystery",
  },
  {
    group: "Mystery",
    value: "Locked-room mystery",
    label: "Locked-room mystery",
  },
  { group: "Mystery", value: "Crime fiction ", label: "Crime fiction " },
  { group: "Mystery", value: "Detective", label: "Detective" },
  { group: "Mystery", value: "Occult detective", label: "Occult detective" },

  {
    group: "Fantasy",
    value: "Action-adventure fiction",
    label: "Action-adventure fiction",
  },
  {
    group: "Fantasy",
    value: "Contemporary fantasy",
    label: "Contemporary fantasy",
  },
  {
    group: "Fantasy",
    value: "Occult detective fiction",
    label: "Occult detective fiction",
  },
  {
    group: "Fantasy",
    value: "Paranormal romance",
    label: "Paranormal romance",
  },
  { group: "Fantasy", value: "Urban fantasy", label: "Urban fantasy" },
  { group: "Fantasy", value: "Cozy fantasy ", label: "Cozy fantasy " },
  { group: "Fantasy", value: "Dark fiction", label: "Dark fiction" },
  { group: "Fantasy", value: "Fairytale", label: "Fairytale" },
  { group: "Fantasy", value: "Fantastique", label: "Fantastique" },
  { group: "Fantasy", value: "Fantasy comedy ", label: "Fantasy comedy " },
  {
    group: "Fantasy",
    value: "Fantasy of manners",
    label: "Fantasy of manners",
  },
  { group: "Fantasy", value: "Gaslamp fiction", label: "Gaslamp fiction" },
  { group: "Fantasy", value: "Gothic fiction", label: "Gothic fiction" },
  { group: "Fantasy", value: "Grimdark fiction", label: "Grimdark fiction" },
  { group: "Fantasy", value: "Hard fantasy ", label: "Hard fantasy " },
  { group: "Fantasy", value: "High fantasy", label: "High fantasy" },
  { group: "Fantasy", value: "Historical ", label: "Historical " },
  { group: "Fantasy", value: "Juvenile fantasy", label: "Juvenile fantasy" },
  { group: "Fantasy", value: "Low fantasy", label: "Low fantasy" },
  { group: "Fantasy", value: "Magic realism ", label: "Magic realism " },
  { group: "Fantasy", value: "Mythic fiction ", label: "Mythic fiction " },
  { group: "Fantasy", value: "Romantic fantasy", label: "Romantic fantasy" },
  { group: "Fantasy", value: "Science fiction ", label: "Science fiction " },
  { group: "Fantasy", value: "Superhero fiction", label: "Superhero fiction" },
  {
    group: "Fantasy",
    value: "Supernatural fiction",
    label: "Supernatural fiction",
  },
  { group: "Fantasy", value: "Weird fiction ", label: "Weird fiction " },
  { group: "Fantasy", value: "Weird Western", label: "Weird Western" },

  { group: "Romance", value: "Amish romance", label: "Amish romance" },
  { group: "Romance", value: "Chivalric romance", label: "Chivalric romance" },
  { group: "Romance", value: "Fantasy romance", label: "Fantasy romance" },
  {
    group: "Romance",
    value: "Contemporary romance",
    label: "Contemporary romance",
  },
  { group: "Romance", value: "Medical romance ", label: "Medical romance " },
  { group: "Romance", value: "Romantic fantasy", label: "Romantic fantasy" },
  {
    group: "Romance",
    value: "Historical romance",
    label: "Historical romance",
  },
  { group: "Romance", value: "Regency romance", label: "Regency romance" },
  {
    group: "Romance",
    value: "Inspirational romance ",
    label: "Inspirational romance ",
  },
  {
    group: "Romance",
    value: "Time-travel romance",
    label: "Time-travel romance",
  },
  { group: "Romance", value: "Romantic suspense", label: "Romantic suspense" },
  { group: "Romance", value: "Western romance", label: "Western romance" },
  {
    group: "Romance",
    value: "Young Adult romance",
    label: "Young Adult romance",
  },
  { group: "Horror", value: "Body horror", label: "Body horror" },
  { group: "Horror", value: "Comedy horror", label: "Comedy horror" },
  { group: "Horror", value: "Zombie comedy", label: "Zombie comedy" },
  { group: "Horror", value: "Ero guro horror", label: "Ero guro horror" },
  { group: "Horror", value: "Ghost stories", label: "Ghost stories" },
  { group: "Horror", value: "Ghostlore", label: "Ghostlore" },
  { group: "Horror", value: "Gothic horror", label: "Gothic horror" },
  { group: "Horror", value: "Japanese horror", label: "Japanese horror" },
  { group: "Horror", value: "Korean horror", label: "Korean horror" },
  {
    group: "Horror",
    value: "Lovecraftian horror",
    label: "Lovecraftian horror",
  },
  { group: "Horror", value: "Monster literature", label: "Monster literature" },
  { group: "Horror", value: "Jiangshi fiction", label: "Jiangshi fiction" },
  { group: "Horror", value: "Werewolf fiction", label: "Werewolf fiction" },
  { group: "Horror", value: "Vampire literature", label: "Vampire literature" },
  {
    group: "Horror",
    value: "Psychological horror",
    label: "Psychological horror",
  },
  { group: "Horror", value: "Splatterpunk", label: "Splatterpunk" },
  { group: "Horror", value: "Techno horror", label: "Techno horror" },
  { group: "Horror", value: "Weird fiction", label: "Weird fiction" },
  { group: "Horror", value: "Weird menace ", label: "Weird menace " },
  { group: "Horror", value: "Zombie apocalypse", label: "Zombie apocalypse" },

  {
    group: "Science Fiction",
    value: "Apocalyptic and post-apocalyptic science fiction",
    label: "Apocalyptic and post-apocalyptic science fiction",
  },
  {
    group: "Science Fiction",
    value: "Christian science fiction",
    label: "Christian science fiction",
  },
  {
    group: "Science Fiction",
    value: "Comedy science fiction",
    label: "Comedy science fiction",
  },
  {
    group: "Science Fiction",
    value: "Utopian science fiction",
    label: "Utopian science fiction",
  },
  {
    group: "Science Fiction",
    value: "Dystopian science fiction",
    label: "Dystopian science fiction",
  },
  { group: "Science Fiction", value: "Cyberpunk ", label: "Cyberpunk " },
  { group: "Science Fiction", value: "Biopunk", label: "Biopunk" },
  { group: "Science Fiction", value: "Dieselpunk", label: "Dieselpunk" },
  {
    group: "Science Fiction",
    value: "Japanese cyberpunk",
    label: "Japanese cyberpunk",
  },
  { group: "Science Fiction", value: "Nanopunk", label: "Nanopunk" },
  { group: "Science Fiction", value: "Solarpunk", label: "Solarpunk" },
  { group: "Science Fiction", value: "Steampunk ", label: "Steampunk " },
  {
    group: "Science Fiction",
    value: "Feminist science fiction",
    label: "Feminist science fiction",
  },
  {
    group: "Science Fiction",
    value: "Gothic science fiction",
    label: "Gothic science fiction",
  },
  { group: "Science Fiction", value: "Osaka", label: "Osaka" },
  {
    group: "Science Fiction",
    value: "Hard science fiction",
    label: "Hard science fiction",
  },
  {
    group: "Science Fiction",
    value: "Climate fiction",
    label: "Climate fiction",
  },
  {
    group: "Science Fiction",
    value: "Parallel world",
    label: "Parallel world",
  },
  {
    group: "Science Fiction",
    value: "Libertarian science fiction",
    label: "Libertarian science fiction",
  },
  {
    group: "Science Fiction",
    value: "Mecha science fiction",
    label: "Mecha science fiction",
  },
  {
    group: "Science Fiction",
    value: "Mecha anime and manga",
    label: "Mecha anime and manga",
  },
  {
    group: "Science Fiction",
    value: "Military science fiction",
    label: "Military science fiction",
  },
  {
    group: "Science Fiction",
    value: "Soft science fiction",
    label: "Soft science fiction",
  },
  {
    group: "Science Fiction",
    value: "Anthropological science fiction",
    label: "Anthropological science fiction",
  },
  {
    group: "Science Fiction",
    value: "Social science fiction",
    label: "Social science fiction",
  },
  { group: "Science Fiction", value: "Space opera ", label: "Space opera " },
  { group: "Science Fiction", value: "Spy-Fi", label: "Spy-Fi" },
  {
    group: "Science Fiction",
    value: "Subterranean science fiction",
    label: "Subterranean science fiction",
  },
  { group: "Science Fiction", value: "Tech noir", label: "Tech noir" },
  {
    group: "Science Fiction",
    value: "Techno-thriller",
    label: "Techno-thriller",
  },
  {
    group: "Science Fiction",
    value: "Science Fantasy ",
    label: "Science Fantasy ",
  },
  { group: "Science Fiction", value: "Dying Earth", label: "Dying Earth" },
  {
    group: "Science Fiction",
    value: "Planetary romance",
    label: "Planetary romance",
  },
  {
    group: "Science Fiction",
    value: "Sword and planet",
    label: "Sword and planet",
  },
];

export const formList = [
  { value: "prose", label: "Prose" },
  { value: "dialogue", label: "Dialogue" },
  { value: "peom ", label: "Poem" },
  { value: "hokku", label: "Hokku" },
  { value: "song", label: "Song" },
];

export const stageList = [
  { value: "none", label: "None" },
  { value: "exposition", label: "Exposition" },
  { value: "rising-action", label: "Rising action" },
  { value: "climax", label: "Climax" },
  { value: "falling-action", label: "Falling action" },
  { value: "resolution", label: "Resolution" },
];

export const languageList = [
  { value: "english", label: "English" },
  { value: "german", label: "Deutsch" },
  { value: "french", label: "Française" },
  { value: "spanish", label: "Español" },
  { value: "russian", label: "Русский" },
  { value: "chinese", label: "中文" },
];

export const levels = ["A0", "A1", "A2", "B1", "B2", "C1", "native"];
